/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cssweb_jnidemo_nfcwrapper */

#ifndef _Included_com_cssweb_jnidemo_nfcwrapper
#define _Included_com_cssweb_jnidemo_nfcwrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cssweb_jnidemo_nfcwrapper
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cssweb_jnidemo_nfcwrapper_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
